name: "Deploy AWS EC2 Exhibition Infrastructure"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform Action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform Infrastructure Automation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Execute Action
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve -input=false
          else
            terraform apply -auto-approve -input=false
          fi